import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{user.isSignedIn ? <SignOutButton /> : <SignInButton />}</div>
        <div>
          <ul>
            {data?.map((post) => (
              <li key={post.id}>{post.content}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
